### ISSUE TITLE
[feature] add/Express+MongoDB+GraphQL

### ISSUE THREAD

**Issue by Kyung-Douhyun** [Jaeja-Phil/cal-culator-mobile-server#5]
### Job Description:

- [x] express + mongodb + graphQl 설정

### Todo:

- [x] server.js 에 mongodb, graphql 연결 코드 작성
- [ ] <s>기존 cal-culator schema re-factoring</s>

### Estimated:

- [ ] 3 hrs
